const arrangedArray = [
     {
        key: 0,
        Country: "Pakistan",
        data: [
           {
            key: 0,
            admin_name: "Sindh",
            capital: "admin",
            city: "Karachi",
            city_ascii: "Karachi",
            country: "Pakistan",
            id: 1586129469,
            iso2: "PK",
            iso3: "PAK",
            lat: 24.86,
            lng: 67.01,
            population: 15292000,
          },
           {
            key: 1,
            "admin_name": "Punjab",
            "capital": "admin",
            "city": "Lahore",
            "city_ascii": "Lahore",
            "country": "Pakistan",
            "id": 1586801463,
            "iso2": "PK",
            "iso3": "PAK",
            "lat": 31.5497,
            "lng": 74.3436,
            "population": 11148000,
          },
           {
            key: 2,
            "admin_name": "Punjab",
            "capital": "minor",
            "city": "Gujranwala",
            "city_ascii": "Gujranwala",
            "country": "Pakistan",
            "id": 1586400472,
            "iso2": "PK",
            "iso3": "PAK",
            "lat": 32.15,
            "lng": 74.1833,
            "population": 2027001,
          },
           {
            key: 3,
            "admin_name": "Punjab",
            "capital": "minor",
            "city": "Bahawalpur",
            "city_ascii": "Bahawalpur",
            "country": "Pakistan",
            "id": 1586038700,
            "iso2": "PK",
            "iso3": "PAK",
            "lat": 29.3956,
            "lng": 71.6722,
            "population": 762111,
          },
          {
            key: 4,
            "admin_name": "Sindh",
            "capital": "minor",
            "city": "Larkana",
            "city_ascii": "Larkana",
            "country": "Pakistan",
            "id": 1586678302,
            "iso2": "PK",
            "iso3": "PAK",
            "lat": 27.56,
            "lng": 68.2264,
            "population": 490508,
          },
          {
            key: 5,
            "city": "Sukkur",
            "city_ascii": "Sukkur",
            "lat": 27.6995,
            "lng": 68.8673,
            "country": "Pakistan",
            "iso2": "PK",
            "iso3": "PAK",
            "admin_name": "Sindh",
            "capital": "minor",
            "population": 499900,
            "id": 1586383591
           },
           {
            key: 6,
            "city": "Rahimyar Khan",
            "city_ascii": "Rahimyar Khan",
            "lat": 28.4202,
            "lng": 70.2952,
            "country": "Pakistan",
            "iso2": "PK",
            "iso3": "PAK",
            "admin_name": "Punjab",
            "population": 353203,
            "id": 1586136399
           },
           {
            key: 7,
            "city": "Okara",
            "city_ascii": "Okara",
            "lat": 30.81,
            "lng": 73.4597,
            "country": "Pakistan",
            "iso2": "PK",
            "iso3": "PAK",
            "admin_name": "Punjab",
            "capital": "minor",
            "population": 232386,
            "id": 1586880900
           },
        ],
      },
      {
        Country: "India",
        data:  [
           {
            "admin_name": "Delhi",
            "capital": "admin",
            "city": "Delhi",
            "city_ascii": "Delhi",
            "country": "India",
            "id": 1356872604,
            "iso2": "IN",
            "iso3": "IND",
            "lat": 28.6667,
            "lng": 77.2167,
            "population": 31870000,
          },
          {
            "admin_name": "Mahārāshtra",
            "capital": "admin",
            "city": "Mumbai",
            "city_ascii": "Mumbai",
            "country": "India",
            "id": 1356226629,
            "iso2": "IN",
            "iso3": "IND",
            "lat": 19.0758,
            "lng": 72.8775,
            "population": 22186000,
          },
          {
            "admin_name": "Mahārāshtra",
            "city": "Pune",
            "city_ascii": "Pune",
            "country": "India",
            "id": 1356081074,
            "iso2": "IN",
            "iso3": "IND",
            "lat": 18.5196,
            "lng": 73.8553,
            "population": 7948000,
          },
           {
            "admin_name": "Gujarāt",
            "city": "Sūrat",
            "city_ascii": "Surat",
            "country": "India",
            "id": 1356758738,
            "iso2": "IN",
            "iso3": "IND",
            "lat": 21.17,
            "lng": 72.83,
            "population": 4875000,
          },
          {
            "admin_name": "Gujarāt",
            "city": "Vadodara",
            "city_ascii": "Vadodara",
            "country": "India",
            "id": 1356705249,
            "iso2": "IN",
            "iso3": "IND",
            "lat": 22.3,
            "lng": 73.2,
            "population": 2065771,
          },
          {
            "city": "Meerut",
            "city_ascii": "Meerut",
            "lat": 28.99,
            "lng": 77.7,
            "country": "India",
            "iso2": "IN",
            "iso3": "IND",
            "admin_name": "Uttar Pradesh",
            "population": 1305429,
            "id": 1356390476
           },{
            "city": "Alīgarh",
            "city_ascii": "Aligarh",
            "lat": 27.88,
            "lng": 78.08,
            "country": "India",
            "iso2": "IN",
            "iso3": "IND",
            "admin_name": "Uttar Pradesh",
            "population": 1131160,
            "id": 1356076391
           },{
            "city": "Mysore",
            "city_ascii": "Mysore",
            "lat": 12.3086,
            "lng": 76.6531,
            "country": "India",
            "iso2": "IN",
            "iso3": "IND",
            "admin_name": "Karnātaka",
            "population": 1014227,
            "id": 1356779323
           },
        ],
      },
       {
        Country: "Australia",
        data: [
          {
            "admin_name": "New South Wales",
            "capital": "admin",
            "city": "Sydney",
            "city_ascii": "Sydney",
            "country": "Australia",
            "id": 1036074917,
            "iso2": "AU",
            "iso3": "AUS",
            "lat": -33.865,
            "lng": 151.2094,
            "population": 4840600,
          },
           {
            "admin_name": "Queensland",
            "capital": "admin",
            "city": "Brisbane",
            "city_ascii": "Brisbane",
            "country": "Australia",
            "id": 1036192929,
            "iso2": "AU",
            "iso3": "AUS",
            "lat": -27.4678,
            "lng": 153.0281,
            "population": 2360241,
          },
          {
            "admin_name": "South Australia",
            "capital": "admin",
            "city": "Adelaide",
            "city_ascii": "Adelaide",
            "country": "Australia",
            "id": 1036538171,
            "iso2": "AU",
            "iso3": "AUS",
            "lat": -34.9275,
            "lng": 138.6,
            "population": 1295714,
          },
           {
            "admin_name": "New South Wales",
            "city": "Central Coast",
            "city_ascii": "Central Coast",
            "country": "Australia",
            "id": 1036067845,
            "iso2": "AU",
            "iso3": "AUS",
            "lat": -33.3,
            "lng": 151.2,
            "population": 297713,
          },
        ],
      },

]

export default arrangedArray